"""transaction model update relationships

Revision ID: 2bdc23bb3e26
Revises: daa6b993d89d
Create Date: 2024-12-13 18:39:16.405091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdc23bb3e26'
down_revision: Union[str, None] = 'daa6b993d89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
